apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    spec:
      organization: {{ .Values.organization }}
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
      dockerEnabled: false
